// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnnNE3TcKfc_Lg_n8OxlcBbgn-e0RKBtE',
    appId: '1:20069081129:web:f88d48f824e0e7a148bc38',
    messagingSenderId: '20069081129',
    projectId: 'nomor2-59d8b',
    authDomain: 'nomor2-59d8b.firebaseapp.com',
    databaseURL: 'https://nomor2-59d8b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nomor2-59d8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4DJKoU1W_6rzGXcgA3sT7RwuyUROXMJA',
    appId: '1:20069081129:android:f52b26e8e43d8d5d48bc38',
    messagingSenderId: '20069081129',
    projectId: 'nomor2-59d8b',
    databaseURL: 'https://nomor2-59d8b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nomor2-59d8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlPLLe2BldVQFvZLWHzBxZXAqNwtl1SOQ',
    appId: '1:20069081129:ios:9dbc92705364a1dd48bc38',
    messagingSenderId: '20069081129',
    projectId: 'nomor2-59d8b',
    databaseURL: 'https://nomor2-59d8b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nomor2-59d8b.appspot.com',
    iosClientId: '20069081129-82ebdne92p6gq9a3bjkdfmvnr2h9o8ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.no2uasmade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlPLLe2BldVQFvZLWHzBxZXAqNwtl1SOQ',
    appId: '1:20069081129:ios:135b9d932e40ccb648bc38',
    messagingSenderId: '20069081129',
    projectId: 'nomor2-59d8b',
    databaseURL: 'https://nomor2-59d8b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nomor2-59d8b.appspot.com',
    iosClientId: '20069081129-t0mduu1b381vdufcjjedc53j46ve4d4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.no2uasmade.RunnerTests',
  );
}
